### ISSUE TITLE
Compatibility with new archive format

### ISSUE THREAD

**Issue by landalex** [davidkrantz/FacebookChatStatistics#1]
The new Facebook archive format is no longer compatible with fbchat-archive-parser, so I wrote a [script](https://github.com/landalex/facebook-message-converter) to convert the new JSON format to fbchat-archive-parser's JSON format to allow me to use your script.

If you'd like me to make a PR either copying the script into this repo or incorporating it into your script, let me know.

**Comment by davidkrantz** [comment]
Thank you for notifying me about the changed format!

You can go ahead and make a PR.
